#!/bin/bash

set -xe

name="rosco"
version="$(date +%Y%m%d%H%M%S)"
deploy_user="vsco"
app_dir="/var/www/$name"
current_dir="$app_dir/current"
deploy_dir="$app_dir/releases/$version"

: ${VSCO:="staging"}

# Build the executable
ssh mango.dev -- "cd /var/www/$name && (git branch | grep \"* master\") && GOROOT=/usr/local/go/v1.4.1 script/cibuild"
# Pull it down from mango
scp mango.dev:/var/www/$name/$name ./$name-${version}
# Grab the nodes for that environment
nodes=$(knife node list | grep "${VSCO}-${name}")

# Deploy!
for node in ${nodes[@]}; do
  SSH="ssh $deploy_user@$node --"
	# Ensure the app's directory is there (for new boxes)
  $SSH "sudo mkdir -p $app_dir"
	# Ensure the deploying user owns the app's directory
  $SSH "sudo chown -R vsco:sysadmin $app_dir"
	# Create the directory for this deploy version
  $SSH "mkdir -p $deploy_dir"
	# Plop the executable up into the versioned directory
  scp ./$name-$version $deploy_user@$node:$deploy_dir/$name
	# Symlink the versioned directory to the current directory.
  $SSH "rm -f $current_dir && sudo ln -s $deploy_dir $current_dir"
	# Restart the service
  $SSH "sudo crank $name"
done
