#!/bin/bash

set -e

./script/cibuild # either it passes the tests, or it doesn't get released

RELEASE=$(./merge-pr -V | awk '{print $2}')

echo "Creating release v$RELEASE"

$EDITOR History.markdown

git add History.markdown
git commit -m "Release :gem: v$RELEASE" || true
git tag -m v$RELEASE -a v$RELEASE
