#!/bin/bash

set -e

./script/cibuild # either it passes the tests, or it doesn't get released

RELEASE=$(./merge-pr -V | awk '{print $2}')

echo "Creating release v$RELEASE"

$EDITOR History.markdown

git add History.markdown
git commit --allow-empty -m "Release :gem: v$RELEASE"
git tag -m v$RELEASE -a v$RELEASE

git push
git push --tags
