#!/bin/bash

set -e

# Make sure we have the correct gom path.

cd "$(dirname "$0")/.."

# Set GOPATH properly
export GOPATH="$(pwd)"

# Run the test

if test -n "$1" && test -e "$1"; then
	if test -d "$1"; then
		dir="$1"
	else
		dir=$(dirname $1)
	fi
else
    dir="."
fi

test -f "$HOME/.netrc" || {
  echo -e "machine api.github.com\n  login travis\n  password terrible" > $HOME/.netrc
}
echo "==> Running tests in '$(pwd)/${dir}'"
pushd $dir > /dev/null
test -z "$(go fmt)" || (echo -e "FAIL\tgo fmt failed." && exit 1)
go test -coverprofile=coverage.out
# go vet || (echo -e "FAIL\tgo vet failed." && exit 1)
popd > /dev/null
